// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = (import.meta as any).env || (typeof process !== 'undefined' ? process.env : {});
const SUPABASE_URL = env.VITE_SUPABASE_URL || "https://uimwgahuyddlscmwfdac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_PUBLISHABLE_KEY || env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase Environment Variables");
  // Render a visible error on the screen if variables are missing
  if (typeof document !== 'undefined') {
    const root = document.getElementById("root");
    if (root) {
      root.innerHTML = `
      <div style="color: red; padding: 20px; font-family: monospace;">
        <h1>Configuration Error</h1>
        <p>Missing Environment Variables.</p>
        <p>Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set.</p>
      </div>
    `;
    }
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY || "", {
  auth: {
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});